# Generated by Django 4.2.7 on 2023-11-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название на английском языке')),
                ('link', models.SlugField(max_length=128, verbose_name='Ссылка')),
                ('color', models.CharField(max_length=128, verbose_name='Название на английском языке')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'post'), (2, 'fact')], default=None, verbose_name='Type')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('title_ru', models.CharField(max_length=256, verbose_name='Заголовок на русском языке')),
                ('title_kz', models.CharField(max_length=256, verbose_name='Заголовок на казахском языке')),
                ('description_ru', models.TextField(verbose_name='Описание на русском языке')),
                ('description_kz', models.TextField(verbose_name='Описание на казахском языке')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
            },
        ),
    ]
