# Generated by Django 4.2.7 on 2023-11-14 15:36

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=posts.models.image_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
