# Generated by Django 4.2.7 on 2023-11-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер для факта'),
        ),
        migrations.AddField(
            model_name='post',
            name='small_description_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Маленькое описание на казахском языке'),
        ),
        migrations.AddField(
            model_name='post',
            name='small_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Маленькое описание на русском языке'),
        ),
    ]
