# Generated by Django 4.2.7 on 2023-11-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educational_institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=125, null=True, verbose_name='Телефон')),
                ('role', models.IntegerField(blank=True, choices=[(1, 'user'), (2, 'director')], default=1, null=True, verbose_name='Роль')),
                ('educational_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_institutions.educationalinstitution', verbose_name='Образовательное учреждение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'users_profiles',
            },
        ),
    ]
