# Generated by Django 4.2.7 on 2023-11-11 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('label', models.CharField(max_length=128, verbose_name='Название поля')),
            ],
            options={
                'verbose_name_plural': 'Charfields',
            },
        ),
        migrations.CreateModel(
            name='CheckField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('label', models.CharField(max_length=128, verbose_name='Название поля')),
            ],
            options={
                'verbose_name_plural': 'Checkfields',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок')),
                ('textarea', models.TextField(blank=True, null=True, verbose_name='Длинный текст')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=polls.models.background_image_path, verbose_name='Задний фон')),
                ('charfields', models.ManyToManyField(to='polls.charfield', verbose_name='Средний текст')),
                ('checkfields', models.ManyToManyField(to='polls.checkfield', verbose_name='Средний текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Опросы',
                'db_table': 'polls',
            },
        ),
    ]
