# Generated by Django 4.2.7 on 2023-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('kz', 'kz')], default='ru', max_length=128, verbose_name='Язык'),
            preserve_default=False,
        ),
    ]
