# Generated by Django 4.2.7 on 2023-11-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='small_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Маленькое описание'),
        ),
    ]
